// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.home.models.FBData' );
goog.provide( 'zz.home.models.FBDataDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.home.models.Tutorial' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.home.models.FBDataDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.stderr = undefined;

    /**
     * @type {boolean}
     */
    this.isrunning = undefined;

    /**
     * @type {zz.home.models.Tutorial}
     */
    this.content = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.home.models.FBDataDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.home.models.FBData = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.home.models.FBData, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.home.models.FBDataDatarow}
*/
zz.home.models.FBData.prototype.DatarowConstructor = zz.home.models.FBDataDatarow;

/**
* Return zz.home.models.FBDataDatarow schema object.
* @override
* @returns {Object}
*/
zz.home.models.FBData.prototype.getDatarowSchema = function( ){

return {
        stderr: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        isrunning: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        content: {
                index: 2,
                type: zz.home.models.Tutorial,
                required: false
        }
};
};