// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.home.models.HelloWorld' );
goog.provide( 'zz.home.models.HelloWorldDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.home.models.HelloWorldDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.text = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.home.models.HelloWorldDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.home.models.HelloWorld = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.home.models.HelloWorld, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.home.models.HelloWorldDatarow}
*/
zz.home.models.HelloWorld.prototype.DatarowConstructor = zz.home.models.HelloWorldDatarow;

/**
* Return zz.home.models.HelloWorldDatarow schema object.
* @override
* @returns {Object}
*/
zz.home.models.HelloWorld.prototype.getDatarowSchema = function( ){

return {
        text: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};