// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.home.models.Images' );
goog.provide( 'zz.home.models.ImagesDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.home.models.ImagesDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.capture = undefined;

    /**
     * @type {string}
     */
    this.source = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.home.models.ImagesDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.home.models.Images = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.home.models.Images, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.home.models.ImagesDatarow}
*/
zz.home.models.Images.prototype.DatarowConstructor = zz.home.models.ImagesDatarow;

/**
* Return zz.home.models.ImagesDatarow schema object.
* @override
* @returns {Object}
*/
zz.home.models.Images.prototype.getDatarowSchema = function( ){

return {
        id: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        capture: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        source: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};