// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.home.models.Layout' );
goog.provide( 'zz.home.models.LayoutDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.ui.models.List' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.home.models.LayoutDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.class = undefined;

    /**
     * @type {string}
     */
    this.icon = undefined;

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {boolean}
     */
    this.disable = undefined;

    /**
     * @type {zz.ui.models.List}
     */
    this.navigation = undefined;

    /**
     * @type {zz.ui.models.List}
     */
    this.menu = undefined;

    /**
     * @type {boolean}
     */
    this.menuOpened = undefined;

    /**
     * @type {boolean}
     */
    this.headerShown = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.home.models.LayoutDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.home.models.Layout = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.home.models.Layout, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.home.models.LayoutDatarow}
*/
zz.home.models.Layout.prototype.DatarowConstructor = zz.home.models.LayoutDatarow;

/**
* Return zz.home.models.LayoutDatarow schema object.
* @override
* @returns {Object}
*/
zz.home.models.Layout.prototype.getDatarowSchema = function( ){

return {
        class: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        icon: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        title: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        disable: {
                index: 3,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        navigation: {
                index: 4,
                type: zz.ui.models.List,
                required: false
        },
        menu: {
                index: 5,
                type: zz.ui.models.List,
                required: false
        },
        menuOpened: {
                index: 6,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        headerShown: {
                index: 7,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};