// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ui.models.List' );
goog.provide( 'zz.ui.models.ListDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ui.models.ListDatarow = function( dataset, opt_data ){

    /**
     * @type {number}
     */
    this.index = undefined;

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.cssClass = undefined;

    /**
     * @type {boolean}
     */
    this.active = undefined;

    /**
     * @type {boolean}
     */
    this.disable = undefined;

    /**
     * @type {string}
     */
    this.icon = undefined;

    /**
     * @type {string}
     */
    this.caption = undefined;

    /**
     * @type {string}
     */
    this.description = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ui.models.ListDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ui.models.List = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ui.models.List, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ui.models.ListDatarow}
*/
zz.ui.models.List.prototype.DatarowConstructor = zz.ui.models.ListDatarow;

/**
* Return zz.ui.models.ListDatarow schema object.
* @override
* @returns {Object}
*/
zz.ui.models.List.prototype.getDatarowSchema = function( ){

return {
        index: {
                index: 0,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        id: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        cssClass: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        active: {
                index: 3,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        disable: {
                index: 4,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        icon: {
                index: 5,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        caption: {
                index: 6,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        description: {
                index: 7,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};