// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.home.models.Tutorial' );
goog.provide( 'zz.home.models.TutorialDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.home.models.Images' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.home.models.TutorialDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {string}
     */
    this.message = undefined;

    /**
     * @type {zz.home.models.Images}
     */
    this.images = undefined;

    /**
     * @type {string}
     */
    this.step = undefined;

    /**
     * @type {string}
     */
    this.author = undefined;

    /**
     * @type {string}
     */
    this.createdTime = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.home.models.TutorialDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.home.models.Tutorial = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.home.models.Tutorial, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.home.models.TutorialDatarow}
*/
zz.home.models.Tutorial.prototype.DatarowConstructor = zz.home.models.TutorialDatarow;

/**
* Return zz.home.models.TutorialDatarow schema object.
* @override
* @returns {Object}
*/
zz.home.models.Tutorial.prototype.getDatarowSchema = function( ){

return {
        id: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        title: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        message: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        images: {
                index: 3,
                type: zz.home.models.Images,
                required: false
        },
        step: {
                index: 4,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        author: {
                index: 5,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        createdTime: {
                index: 6,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};