// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.home.models.View' );
goog.provide( 'zz.home.models.ViewDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.home.models.ViewDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.name = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.home.models.ViewDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.home.models.View = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.home.models.View, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.home.models.ViewDatarow}
*/
zz.home.models.View.prototype.DatarowConstructor = zz.home.models.ViewDatarow;

/**
* Return zz.home.models.ViewDatarow schema object.
* @override
* @returns {Object}
*/
zz.home.models.View.prototype.getDatarowSchema = function( ){

return {
        name: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};